### ISSUE TITLE
distributed zulip store: restore zulip from on-chain mirror

### ISSUE THREAD

**Issue by dckc** [rchain-community/rchat-fork#10]
@leithaus asked if the on-chain mirror is sufficient to stand up another zulip server with the same history, ready to continue.

This restore feature depends on getting the mirror / backup part to be reliable as well:
  - [x] on-chain rchain-community/rv2020#19
  - [ ] delivery, order rchain-community/rchat-fork#3
  - [x] enough phlo rchain-community/rv2020#43
  - [ ] validAfterBlockNumber rchain-community/rchat-fork#6 
  - [ ] no 1 validator should be a SPOF rchain-community/rchat-fork#5 
  - [ ] mirror all tables rchain-community/rchat-fork#4
